# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20180926_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='user',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='department.Department'),
        ),
    ]
