# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 05:01
from __future__ import unicode_literals

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='visa_expire',
            field=encrypted_fields.fields.EncryptedDateTimeField(),
        ),
    ]
